version: "2"

volumes:
  dados:
networks:
  banco:
  web:
  fila:

services:
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:latest
    volumes:
      # Site
      - ./web:/usr/share/nginx/html
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    environment:
      - DB_NAME=email_sender
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue

  worker:
    build: worker
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks:
      - fila
    depends_on:
      - queue
      - app
  queue:
    image: redis:latest
    networks:
      - fila
